<a href="https://colab.research.google.com/github/Tkei-54/skills-introduction-to-github/blob/main/Numpy_for_dummies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#creating a numpy array
data = [1,2,3,4,5]

arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [ ]:
#creating a 2d array using array() function
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
data3 = [[1,2,3],[4,5,6],[7,8,9]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
zeros_arr = np.zeros((3,3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones_arr = np.ones((3,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
full_arr = np.full((3,3),5)
full_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
empty_arr = np.empty((3,3))
empty_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

In [ ]:
#elementwise operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
#elementwise operations on 2D arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#elementwise operations on 3D arrays
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b = np.array([[[9,10],[11,12]],[[13,14],[15,16]]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]
[[[-8 -8]
  [-8 -8]]

 [[-8 -8]
  [-8 -8]]]
[[[  9  20]
  [ 33  48]]

 [[ 65  84]
  [105 128]]]
[[[0.11111111 0.2       ]
  [0.27272727 0.33333333]]

 [[0.38461538 0.42857143]
  [0.46666667 0.5       ]]]


In [ ]:
#unary operations on 1D arrays
a = np.array([1,2,3,4])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.var(a))
print(np.exp(a))
print(np.log(a))
print(np.power(a,2))

10
2.5
4
1
1.118033988749895
1.25
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 1  4  9 16]


In [ ]:
#binary operations
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [ ]:
#basic indexing
a = np.array([1,2,3,4,5])
print(a[0])
print(a[1])
print(a[-1])
print(a[-2])

1
2
5
4


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0,0])
print(arr2[0,1])
print(arr2[1,0])
print(arr2[1,1])

1
2
4
5


In [ ]:
#slicing
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0:3])
print(a[3:6])
print(a[6:9])
print(a[1:9:2])

[1 2 3]
[4 5 6]
[7 8 9]
[2 4 6 8]


In [ ]:
import numpy as np

In [ ]:
#Advanced Indexing
arr = np.array([1,2,3,4,5,6,7,8,9])
indices = [0,2,4,6,8]
print(arr[indices])

[1 3 5 7 9]


In [ ]:
#boolean indexing
arr = np.array([10,20,30,40,50])
mask= arr>35
print(arr[mask])
print(arr[arr%20==0])

[40 50]
[20 40]


In [ ]:
#Broadcasting
A = np.array([[1],[2],[3]])
B = np.array([10,20,30,40])
C = A + B
print(C)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [ ]:
#Broadcasting incompatible shapes
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10])
C = A + B
print(C)

[[11 12 13]
 [14 15 16]]
